name: static_file_handler
version: 0.2.2
author: Daniele Salatti <danielesalatti@gmail.com>
description: A static file Web server written in Dart
homepage: https://github.com/DanieleSalatti/dart-static-file-handler
environment:
  sdk: '>=1.1.3 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.11.0'
  yaml: '>=0.9.0 <0.10.0'
dev_dependencies:
  path: '>=1.0.0 <2.0.0'
  route: '>=0.4.6'
  unittest: '>=0.9.0 <0.10.0'
